###
GET http://localhost:5000/user

###
GET http://localhost:5000/user/1

###
POST http://localhost:5000/user
Content-Type: application/json
{
    "name":"Bernard",
    "email": "beber@hotmail.com"
}

###
PUT http://localhost:5000/user/1
Content-Type: application/json
{
    "name": "Gilbert"
}

###
DELETE http://localhost:5000/user/1
